# Generated by Django 3.1.7 on 2021-03-10 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='dep_date',
            field=models.DateField(default=datetime.date(2021, 3, 10)),
        ),
    ]
