# Generated by Django 3.1.7 on 2021-03-11 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20210311_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='dep_date',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='dep_time',
        ),
        migrations.AddField(
            model_name='flights',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
