# Generated by Django 3.1.7 on 2021-03-11 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210311_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
