# Generated by Django 3.1.7 on 2021-03-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20210311_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='offer',
        ),
        migrations.AddField(
            model_name='flights',
            name='available_seats',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_seats', models.IntegerField(default=1)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.flights')),
            ],
        ),
    ]
