# Generated by Django 3.1.7 on 2021-03-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20210313_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='flight',
            new_name='flights',
        ),
    ]
