# Generated by Django 3.1.7 on 2021-03-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20210313_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='no_seats',
        ),
    ]
