# Generated by Django 3.1.7 on 2021-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_tickets_no_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='no_seats',
            new_name='num_seats',
        ),
        migrations.AddField(
            model_name='tickets',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
