# Generated by Django 3.1.7 on 2021-03-24 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20210316_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_age', models.IntegerField()),
                ('seat_num', models.IntegerField()),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.flights')),
            ],
        ),
    ]
